---
# Role handlers

- name: Halt
  shell: >-
    sleep {{ halt_delay }}
    && shutdown -h now 'Ansible halt role triggered a halt'
  args:
    warn: no
  async: 1
  poll: 0
  changed_when: true
  ignore_errors: true
  listen:
    - halt host
    - halt
  when:
    - ansible_virtualization_type | default("") != "docker"
    - not halt_disable
  check_mode: no
